### ISSUE TITLE
API to get average review score

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#34]
<img width="475" alt="image" src="https://github.com/eronka/culero/assets/4149765/e7b67890-721d-48e7-8faa-314789bdab55">

API to get user's average review score 1. overall 2. each category (professionalism/ reliability / communication).

1 API for logged in user
2 API for other user's profile

What would be the best way to handle the caching this?

**Comment by mehulmathur16** [comment]
@hsb1007 can I be assigned?

**Comment by mehulmathur16** [comment]
@hsb1007 Thanks for assigning.

**Comment by rajdip-b** [comment]
Adding a comment to address the caching issue:

Considering that we have a caching layer set (using nest cache or anything else), we can follow this approach:
- We maintain a key witht the user id. The relation will be `userId -> score`
- Whenever the review data is updated/added, we first write the data in the db, then we compute the score, then we add it in cache asynchronously.
- Whenever we try retrieving the data, we can check the cache for `userId`, see if the key is present. If yes, return it. If no, compute the score, store the cache, return the data.

P.S. for better performance, we can use `pg-boss` to schedule jobs to run on postgres since we are already using psql.

@hsb1007 thoughts?

**Comment by hsb1007** [comment]
> > Adding a comment to address the caching issue:
> > Considering that we have a caching layer set (using nest cache or anything else), we can follow this approach:
> > 
> > * We maintain a key witht the user id. The relation will be `userId -> score`
> > * Whenever the review data is updated/added, we first write the data in the db, then we compute the score, then we add it in cache asynchronously.
> > * Whenever we try retrieving the data, we can check the cache for `userId`, see if the key is present. If yes, return it. If no, compute the score, store the cache, return the data.
> > 
> > P.S. for better performance, we can use `pg-boss` to schedule jobs to run on postgres since we are already using psql.
> > @hsb1007 thoughts?
> 
> Sounds awesome! @mehulmathur16 can you please incorporate this?

@mehulmathur16  All good, I will raise it as a separate issue!

**Comment by mehulmathur16** [comment]
@hsb1007 I'll look into this.
