### ISSUE TITLE
Adding Testing framework for backend and add test cases for existing APIs

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero#45]
Hi team,

Can someone add a testing framework and add simple test cases for each API we already have?

While the project is still very infancy stage, I would like to include this into our backend

Please recommend the best test framework

**Comment by Rutik7066** [comment]
If any one wants to take on this Here is the doc from official NestJs : https://docs.nestjs.com/fundamentals/testing

**Comment by guptadeepak8** [comment]
/attempt #45
Can i get assigned

**Comment by hsb1007** [comment]
> /attempt #45 Can i get assigned ?
> 
> [Algora profile](https://console.algora.io/@/guptadeepak8)	Completed bounties	Tech	Active attempts	Options
> @guptadeepak8	6 bounties from 4 projects	
> TypeScript, Svelte,
> JavaScript & more
> [Cancel attempt](https://console.algora.io/api/bounties/cltrr7wef0006jx0f0wbhubf0/cancel-attempt)

Good luck!

**Comment by rajdip-b** [comment]
@guptadeepak8 hey bro, there are two ways to go about this: unit testing and e2e testing. Generally I would add unit tests to helper functions but at the time, there aren't any. I would suggest you to move with e2e tests. I'm leaving a link to a project where I implemented e2e tests in nestjs and would be a good read for you!

https://github.com/keyshade-xyz/keyshade/tree/develop/apps/api

The tests are in every modules' `.e2e.spec` files. Also, I set up a postgres intance locally using docker compose in here so that i dont have to fake the prisma layer.

**Comment by guptadeepak8** [comment]
> @guptadeepak8 hey bro, there are two ways to go about this: unit testing and e2e testing. Generally I would add unit tests to helper functions but at the time, there aren't any. I would suggest you to move with e2e tests. I'm leaving a link to a project where I implemented e2e tests in nestjs and would be a good read for you!
> 
> https://github.com/keyshade-xyz/keyshade/tree/develop/apps/api
> 
> The tests are in every modules' `.e2e.spec` files. Also, I set up a postgres intance locally using docker compose in here so that i dont have to fake the prisma layer. 

@rajdip-b Thanks bro

**Comment by guptadeepak8** [comment]
hey @rajdip-b you can take this one

**Comment by guptadeepak8** [comment]
hey @rajdip-b you can take this one

**Comment by rajdip-b** [comment]
Sure thing boss! @guptadeepak8 . @hsb1007 can you assign this to me?
